[build]
  # Build command (if you have one)
  command = "echo 'No build process required for static site'"

  # Directory to publish
  publish = "netlify-deploy"

[build.environment]
  NODE_VERSION = "18"

# Redirect rules
[[redirects]]
  from = "/demo"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://*.tile.openstreetmap.org data:; img-src 'self' https://*.tile.openstreetmap.org data:; connect-src 'self'"

# Cache static assets
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "max-age=3600"